name: 自动获取ss节点

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: 获取仓库代码
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false

      - name: 执行脚本并提取ss链接
        run: |
          ./ss | awk '/^ss:\/\//{ print $0 }' > out.txt

      - name: 提交更新的out.txt
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add out.txt
          git commit -m "Update ss links" || exit 0

      - name: 推送更改
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: 上传结果文件
        uses: actions/upload-artifact@v3
        with:
          name: ss-links
          path: out.txt
